### PR TITLE
Add the full expected location for the data directory

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Copying the data directory directly into ~/.local/share/swarm does not work, this commit prevents that mistake.

### CODE REVIEW

**Comment by byorgey** [comment]
Looks like the restyled error was spurious --- I'm not sure how to rerun it though.

**Review by byorgey — APPROVED** [review]

**Comment by kostmo** [comment]
> not sure how to rerun it though

Rebasing on `main` should fix it.

**Review by xsebek — APPROVED** [review]
> Copying the data directory _[contents]_ directly into `~/.local/share/swarm` does not work, this commit prevents that mistake.

Not sure what the semantics are, but I would say `copy -r data swarm` creates `swarm/data`. 😁 

I agree the new version is clearer. 👍

**Comment by xsebek** [comment]
@TristanCacqueray can you rebase on the main branch, please? :slightly_smiling_face:

**Review by byorgey — APPROVED** [review]

**Pull request merged**
