### PR TITLE
Delete stack.yaml

### LINKED ISSUE #1960: Delete `stack.yaml`
Stack currently cannot compile swarm on windows and I think it is currently not recommended.

However, we still have a stack.yaml, which is very annoying for me because VS Code defaults to stack, so I have to delete it manually every time I pull, and then explicitly not stage the deletion when I commit.

### PR DESCRIPTION
**Pull request by noahyor**
Delete stack.yaml

Closes #1960.

### CODE REVIEW

**Review by byorgey — APPROVED** [review]

**Comment by xsebek** [comment]
@noahyor why not get rid of the HIE stack file and make the cabal one default?

**Comment by noahyor** [comment]
Done.

**Comment by noahyor** [comment]
We should also change the mergify rules accordingly.

**Comment by nitinprakash96** [comment]
Since `hie.yaml` now defaults to cabal cradle, should it be committed to repository? If not, then I think we should still keep `hie.yaml` in `.gitignore`.

**Comment by byorgey** [comment]
You're right, let's remove `hie.yaml` and add it to `.gitignore`.

**Pull request merged**
