### PR TITLE
Generate other wikis

### LINKED ISSUE #344: Create command line tools to automate documentation
It would be nice to have either a separate executable or a new parameter to generate documentation.

Some ideas:

- [x] We have nice cheatsheets on the Wiki that are hard to keep up to date. Generate those markdown tables from code.
  - [x] **Commands** (name, type, capability, description) #531
  - [x] **Capabilities** (name, install, commands, description)
  - [x] **Entities** (character, name, capabilities, properties, portable)
  - [x] **Recipes** (in, out, required, time)
- [x] Recipe dependencies graph #476
- [x] Editor keywords  #526

### PR DESCRIPTION
**Pull request by xsebek**
- generate wiki for:
  - entities
  - recipes (table and added recipe graph image)
  - capabilities (only table)
- properly parse command line argument for `generate cheatsheet`
- closes #344

### CODE REVIEW

**Comment by byorgey** [comment]
Links on the new recipes and capabilities pages seem to be broken, they are missing `/wiki/`.

**Review by byorgey — APPROVED** [review]
I don't plan to read every line of code carefully. :smile:  But the generated wiki pages look good (other than the broken links, which I suspect is not a problem with the code but rather with the flags passed on the command line).

**Comment by xsebek** [comment]
@byorgey I am passing `--entities-page='../Entities-cheat-sheet'` because it is the relative address on our Wiki.

But if we or someone else wants to use it outside the Wiki then absolute links will be necessary.

---

I will check why the links are broken, I must have made some silly mistake. 😅

**Comment by xsebek** [comment]
OK, so what confused me is that relative links work in the Wiki editor preview but then not on the page once saved.

I fixed it by using absolute links. 🙂

**Comment by byorgey** [comment]
Would it not work to just say e.g. `--commands-page='Commands-Cheat-Sheet' ?

**Pull request merged**
