### PR TITLE
Returns to the scenario menu after winning a game

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change slightly improves the navigation by saving
the menu position so that the user gets back to the next
tutorial or challenge after winning a game.

### CODE REVIEW

**Review by byorgey — APPROVED** [review]

**Review by xsebek — APPROVED** [review]
Feels great to be back in the menu where I just was :+1: 

Maybe I am missing something, but how do I quit the game fastest now?
It used to be <kbd>Ctrl</kbd><kbd>Q</kbd> then <kbd>-></kbd> and <kbd>Enter</kbd> and then finally <kbd>Ctrl</kbd><kbd>Q</kbd> again in the menu, but now I have to press it as many times as I am deep in scenario hierarchy.

**Comment by TristanCacqueray** [comment]
@xsebek b933c11 should restore that workflow, e.g. <kbd>Ctrl</kbd><kbd>Q</kbd> now quit the game from any menu.

**Comment by xsebek** [comment]
@TristanCacqueray you can tick the checkbox in #356 after you merge this, sadly it did not get its own issue. :wink:

**Comment by TristanCacqueray** [comment]
Oops, I merged too soon. When starting the game with the `-s` argument, then the exit dialog no longer exit the game.

**Comment by xsebek** [comment]
@TristanCacqueray yes, but that was the old behaviour, so I don't blame you for not changing that in this PR :wink:

**Pull request merged**
