### PR TITLE
Use IntSet for WindowedCounter

### PR DESCRIPTION
**Pull request by kostmo**
Towards #1558.

### CODE REVIEW

**Review by byorgey — COMMENTED** [review]
So what would happen on a system with a 32-bit `Int` type which is left running long enough to cause overflow?

**Comment by kostmo** [comment]
> So what would happen on a system with a 32-bit `Int` type which is left running long enough to cause overflow?

Hmm... I suppose the `IntSet` might start growing without bound.  May be worth catching that edge case and writing a new unit test.

**Comment by xsebek** [comment]
@kostmo could you close the window at maxBound of Int? Afterwards it can start clean from minBound and comparison should always make sense.

If maxBound is evenly divisibly by window size, then it will even be correct.

**Comment by byorgey** [comment]
We could also just leave it as `Integer`, since we know that will be correct, and we're already doing other things to mitigate the performance impact of the `WindowedCounter`.  I don't know how much of a difference using an `IntSet` will make in practice.

**Comment by kostmo** [comment]
Closing this for now, since it's not certain that it is needed.

**Pull request closed without merging**
