### PR TITLE
0.4 release

### LINKED ISSUE #1316: 0.4 release!
It's been a while since the last release.  I started updating the CHANGELOG for an 0.4 release on this branch: https://github.com/swarm-game/swarm/tree/release-0.4

### PR DESCRIPTION
**Pull request by byorgey**
Closes #1316 .

### CODE REVIEW

**Comment by byorgey** [comment]
@kostmo , @xsebek , what do you think?  Let's put out an 0.4 release!

**Comment by byorgey** [comment]
I could also throw together a blog post about it if we think it's worth publicizing.

**Comment by xsebek** [comment]
Lots of improvements! 👍 

I would like to follow it up with VSCode plugin version bump and release with the new keywords. Hopefully it’s just about pushing a tag. 🙂

**Comment by xsebek** [comment]
@byorgey btw. I am slowly working through the bibiliography section of your World DSL blog post. 😄 Maybe it would be good to call out this application of it and list other fun improvements. 🙂

**Comment by byorgey** [comment]
In any case, the official release doesn't have to wait for the blog post.  But someone has to approve this PR before I can merge it. :smile:

**Review by kostmo — APPROVED** [review]
Did we call out the improved pedagogy (and its enforcement/validation through CI) of the tutorials?  (Belongs thematically with markdown rendering)

Some thoughts on the upcoming blog post:
* the scenario launch enhancement and scoring methods lay groundwork for competitive play
* Structure templates, subworlds and map DSL, along with the slew of new robot commands, belong thematically together as substantially expanding creative possibilities for scenario design

**Pull request merged**
