### PR TITLE
Wait for windows

### LINKED ISSUE #2032: Mergify doesn't wait for Windows CI
Mergify merged and deleted a branch before Windows CI had finished.

### PR DESCRIPTION
**Pull request by xsebek**
Closes #2032.

Add windows to mergify

### CODE REVIEW

**Review by byorgey — APPROVED** [review]
Thanks! Not sure how I missed this!

**Review by noahyor — APPROVED** [review]
I feel like this is good practice for now, but the windows CI takes >20 min sometimes!

**Comment by byorgey** [comment]
> I feel like this is good practice for now, but the windows CI takes >20 min sometimes!

For some reason it seems like the caching does not work very well for the Windows build --- it seems like every time there is a cache miss and it has to build every single dependency from scratch.  I think this accounts for the discrepancy in build times but I have no idea what to do about it.

**Comment by xsebek** [comment]
@byorgey I noticed it as well, but I have not figured it out yet.

The solution is probably to copy the Haskell-CI pattern. Recent discussion: https://discourse.haskell.org/t/github-cache-action/9926/8

**Pull request merged**
