### PR TITLE
The great `install`/`equip` switch

### LINKED ISSUE #907: Remove "Install" command
This is a follow-up to #887.

### PR DESCRIPTION
**Pull request by byorgey**
Closes #907.

- Add a recipe for `welder` device (which provides `equip`/`unequip`)
  - Recipe = 2 `copper wire` + 1 `copper pipe` + 1 `iron plate` + 1 `I/O cable` (transitively requires `furnace` + 1.5 ` copper ore` + 0.5 `iron ore` + 3.5 `log` + 1 `LaTeX`).
  - This recipe was suggested by @noahyor.  It requires a bit of wood, a bit of copper, a bit of rubber, and a bit of iron, so a nice mid-game recipe (you need to already have a drill, but not much else).
- Get rid of the `install` command
- Update all "install" references to "equip"
- Start `base` with a `welder` in classic mode, and in `world101` and `farming` tutorials.
    - The `base` used to be able to install stuff on itself with `install base`, so this is just preserving the capabilities the base already had.
- Require a `welder` as catalyst for making `tank treads`
    - No particular reason, just seemed like fun.

### CODE REVIEW

**Comment by byorgey** [comment]
I know this will probably generate merge conflicts with everything, but oh well.  We can definitely hold off on merging this if it's easier to merge some other things first and then I'll fix up the merge conflicts in this PR.

**Comment by byorgey** [comment]
I particularly wanted a recipe for `welder` so I can actually use it in classic mode, but then I got carried away. :smile:

**Review by kostmo — APPROVED** [review]
Nice! Let's get this in to minimize duration of any merge conflicts.

**Comment by byorgey** [comment]
@xsebek , any thoughts?

**Review by xsebek — APPROVED** [review]
I like it - `equip` instead of `install self` is a nice improvement and does not require mirror. 👍

**Pull request merged**
