### PR TITLE
Faster sheep check

### PR DESCRIPTION
**Pull request by xsebek**
This seeks to improve the performance of contained sheep checks.

The results were surprising, discuss below. 😕

### CODE REVIEW

**Comment by kostmo** [comment]
FYI I just fixed a bug in my own solution and force-pushed my branch, so you may want to rebase.  I'll stop force-pushing for now while we look at this PR.

**Comment by xsebek** [comment]
@kostmo I am tired of this and it's broken (I was switching between alternatives), but I will write down my notes:

- checking all sheep makes everything **3x slower** and it is unavoidable (while they all live free)

- following a path and checking for left, right and forward is **slower than expected**
     - opportunistic going forward if possible would likely speed this up

- parsing the condition check once **makes a huge difference, 2x to 3x speedup**
    - this should be solved by #495
    - in the meantime inlining the file to the condition works

- checking if there are fences added from both sides results in **no lag until the fence is finished**
    - this would be best implemented using #687
    - here I broke the solution, as I was tired, but I think it worked for me briefly 
    - this is an automated version of "say when ready" assuming that the goal is to connect to the original gate

---

@kostmo I think we should measure the solutions and choose the most correct and fastest one. 

Yours was pretty fast, but it only checked one sheep so it did not suffer from the 3x slowdown.

A properly optimized correct solution could run under 5s, but when it's around 10s it at least feels fast enough.

**Comment by kostmo** [comment]
Awesome, thank you for the thorough investigation!  I will incorporate these optimizations.

**Comment by xsebek** [comment]
Closing, as @kostmo implementation is now pretty optimised. :slightly_smiling_face:

**Pull request closed without merging**
