### PR TITLE
Start base with finite supply of basic robot parts

### LINKED ISSUE #35: Starting base with a large but finite supply of basic robot parts
Right now, the base can build infinitely many robots with basic devices: a detonator, grabber, solar panel, and treads.  However, it is a bit unrealistic that we can make infinitely many of these.  Well, not that the game is realistic, but you know what I mean.  It might be worth considering instead:

* Do not any longer install those devices on robots by default; they must be available in the inventory just like any other device.
* Start the base out with a large number (100? 500? 1000?  maybe the number depends on the difficulty level? maybe different numbers of different devices, e.g. fewer detonators than treads?) of these devices, so that at the start of the game the user can construct a bunch of basic robots "for free", but will eventually have to think about producing more of these devices.
* In order to make this work, we also have to come up with recipes for these devices, and think carefully about how to balance the depth and difficulty.

### PR DESCRIPTION
**Pull request by byorgey**
There is no longer a list of "default devices" which can be generated out of thin air.

Closes #35.

### CODE REVIEW

**Comment by xsebek** [comment]
@byorgey I hope you won't mind that I updated the description with #395 :slightly_smiling_face:

**Comment by byorgey** [comment]
@xsebek perfect, thanks!

**Comment by byorgey** [comment]
A recipe for a `plasma cutter` is the only thing left!  Any ideas?

**Comment by byorgey** [comment]
Technically we should probably update `TUTORIAL.md` to match,  but I'm getting sick of updating it, and would rather focus on #25 .

**Review by xsebek — APPROVED** [review]
:+1:

**Comment by byorgey** [comment]
@xsebek what do you think?

**Comment by xsebek** [comment]
The toolkit recipe seems fine to me :slightly_smiling_face: I checked the recipe graph and it's about the same difficulty as the other starting devices.

**Review by TristanCacqueray — APPROVED** [review]
:+1:

**Comment by byorgey** [comment]
I called it a `toolkit` instead of a `repair kit` since if you are taking robots apart you are obviously not repairing them. :grin:  Hopefully we can find other uses for a `toolkit` later.

**Comment by byorgey** [comment]
@mergifyio refresh

**Pull request merged**
