### PR TITLE
Publish VSCode extension under swarm-game everywhere

### LINKED ISSUE #1453: Publish VSCode plugin also on the free VSX marketplace
_VSCodium_ uses a different FLOSS marketplace: https://open-vsx.org

We should publish the plugin there as well so that both editors can search for "swarm" extension.

- [x] Get a namespace EclipseFdn/open-vsx.org#2066
- [x] Upload current extension version
- [ ] Update VSCode CI to push the extension to Open-VSX

### PR DESCRIPTION
**Pull request by xsebek**
* move the VSCode extension under "swarm-game" organisation
* add Open VSX Registry to "Deploy Extension" GitHub Action
* bump version, so it gets pushed once tagged
* closes #1453

### CODE REVIEW

**Review by byorgey — APPROVED** [review]
I don't pretend to understand any of this but it seems reasonable and I trust you. :smile:

**Comment by xsebek** [comment]
@byorgey previously the extension was published only on microsoft marketplace under namespace `xsebek`.

From now on, it will be under namespace `swarm-game` both on microsoft marketplace and open vsx repository. That is, once I get home and push a tag. 🙂

**Comment by xsebek** [comment]
Btw. if anyone wants to join the organisation on either one (@kostmo?) I can send an invite. 😉

**Comment by kostmo** [comment]
> if anyone wants to join the organisation on either one

Sure, I'll join both

**Pull request merged**
