### PR TITLE
Bump checkout and setup-node actions to v4

### PR DESCRIPTION
**Pull request by nitinprakash96**
All checkout actions prior v4 use NodeJS 16 which has been deprecated by github actions. 
Same is the case with setup-node@v1.

### CODE REVIEW

**Review by byorgey — APPROVED** [review]
Makes sense, thanks!

**Comment by byorgey** [comment]
@nitinprakash96 now that the PR has been approved, feel free to add the `merge me` label yourself to trigger the automatic merge process.

**Comment by nitinprakash96** [comment]
Thanks!

**Comment by byorgey** [comment]
@nitinprakash96 by the way, since you now have push access, you're welcome to create feature branches directly in this repo (rather than in your own fork) and then open PRs from those branches to `main`.  This actually works better with some aspects of our CI.

**Pull request merged**
