### PR TITLE
Erase the erase function

### PR DESCRIPTION
**Pull request by xsebek**
* simplify the `erase` function using the `Functor` instance

### CODE REVIEW

**Review by byorgey — APPROVED** [review]
:exploding_head:

**Comment by byorgey** [comment]
Wait, actually, now I am having second thoughts, is this new implementation really equivalent to the old one?

**Comment by xsebek** [comment]
@byorgey it passes tests, so I think it's pretty equivalent (up to our test coverage). 😄 

I have been using `void` occasionally when I needed to get rid of the types and did not know about `erase`.

I there is a reason for dropping `SrcLoc`?

**Comment by byorgey** [comment]
> Is there is a reason for dropping `SrcLoc`?

No, there's not, which is why I think `void` is better!

**Pull request merged**
